<?php
function shift_cipher_menu() {
    $item = array();
    $items['shift_cipher'] = array(
        'title' => "Shift Cipher",
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['cipher_results_page'] = array(
        'title' => "Cipher Message:",
        'page callback' => 'cipher_results',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function shift_cipher_form() {
    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => t('Enter a number'),
    );
    $form['shift_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => t('Enter a direction (left or right)'),
    );
    $form['phrase'] = array(
        '#title' => 'Phrase',
        '#type' => 'textfield',
        '#description' => t('Enter a the phrase to encrypt)'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt',
    );
    return $form;
}

function shift_cipher_form_submit($form, &$form_state) {
    $shift_value = $form_state['values']['shift_value'];
    $shift_value = intval($shift_value);
    $shift_direction = $form_state['values']['shift_direction'];
    if ($shift_direction === "left") {
        $direction = -1;
    } else {
        $direction = 1;
    }
    $phrase = $form_state['values']['phrase'];
    $phrase = strtolower($phrase);
    $letters = str_split($phrase);
    $alphabet = array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z');
    //$z = 25;
    $encrypted_message = "";
    foreach ($letters as $letter) {
        $alphabet_index =  array_search($letter, $alphabet);
        if (in_array($letter, $alphabet)) {
            $new_index = $alphabet_index + ($shift_value * $direction);
            if ($new_index > 25) {
                $new_index = $new_index - 26;
            } elseif ($new_index < 0){
                $new_index = $new_index + 26;
            }
            $new_letter = $alphabet[$new_index];
        } else {
            $new_letter = $letter;
        }
        $encrypted_message .= $new_letter;
    }
    $_SESSION['encrypted_message'] = $encrypted_message;
    $form_state['redirect'] = 'cipher_results_page';
}

function cipher_results() {
    $encrypted_message = $_SESSION['encrypted_message'];
    $result = "<p>$encrypted_message</p>";
    return $result;
}
